"""The guide a jury can hold has to be the guide the product ships.

`docs/USER_GUIDE.md` is generated by `tools/guide.py` out of the capability
manifest, `config.toml` and the triage code itself, so it cannot describe a
MedBox that does not exist. That guarantee is only worth anything if somebody
regenerates it after changing the product, and nobody remembers to. This is
the somebody.

If this test fails, nothing is broken: run `python tools/guide.py` and commit
what it writes.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.guide import band_rows, build, main, scenarios  # noqa: E402


def test_the_committed_guide_is_up_to_date():
    assert main(["--check"]) == 0, (
        "docs/USER_GUIDE.md is out of date. Run: python tools/guide.py"
    )


def test_the_bands_are_read_out_of_the_scoring_code():
    """Transcribing the thresholds into prose is how a guide ends up
    describing a version of NEWS2 the code stopped using, so they are derived
    by running band() over every aggregate it can produce."""
    rows = band_rows()
    names = [name for _, name, _ in rows]
    assert names == ["routine", "low", "medium", "high"], names
    assert all(response for _, _, response in rows), "a band with no action"


def test_every_scenario_reaches_the_guide():
    """An operator who cannot find out what the demo scenario does has to
    read YAML to run the demo."""
    stems = {stem for stem, _, _ in scenarios()}
    on_disk = {p.stem for p in (ROOT / "scenarios").glob("*.yaml")}
    assert stems == on_disk, f"missing from the guide: {on_disk - stems}"
    for stem, title, description in scenarios():
        assert title and title != stem, f"{stem} has no readable name"
        assert description, f"{stem} is listed with nothing said about it"


def test_the_guide_never_promises_the_assistant_is_required():
    """The whole claim of this project is that most of it runs without a
    model. A guide that quietly reads as AI-first undoes that in the one
    document a jury takes away."""
    text = build()
    assert "Works with the assistant dead" in text
    assert "Needs the assistant" in text
    # Section 7 is the kill demo, and it has to be in the document, not only
    # on stage.
    assert "Kill Ollama mid-consultation" in text
