"""Builds docs/USER_GUIDE.md out of the product itself.

There are two guides in this project and they must never disagree.

One is on the screen: press Help and the station renders what it can do, what
it refuses to do, and every phrase you can type at it. The other is the one a
jury can hold, print and mark. A hand-written second guide would be correct on
the day it was written and wrong by the demo, because the only thing keeping
it true would be somebody remembering.

So the paper guide is generated. Everything factual in it is read out of the
code that has to honour it:

  - what it does, will not do, and answers to   server/ai/capabilities.py
  - the crew, the zones, the port, the model     config.toml
  - the NEWS2 bands                              server/triage.py, by running it
  - the scenarios                                scenarios/*.yaml

`--check` regenerates and compares, and a test runs it. Change a capability
and forget the guide, and the suite says so before a reader does.

Standard library only, and so is everything it imports, so this runs on a bare
`python` with nothing installed. A document you cannot rebuild because the
virtual environment is broken is a document you will ship stale.
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from server.ai.capabilities import (  # noqa: E402
    CAPABILITIES,
    REFUSALS,
    SHORTCUTS,
)
from server.ai.schemas import FIT_LEVELS, SIGN_SOURCES  # noqa: E402
from server.config import CONFIG  # noqa: E402
from server.triage import Urgency, band  # noqa: E402

OUT = ROOT / "docs" / "USER_GUIDE.md"
SCENARIO_DIR = ROOT / "scenarios"

BANNER = (
    "<!-- Generated by tools/guide.py from the product itself. Do not edit by "
    "hand: run `python tools/guide.py` instead, or the next run overwrites you. -->"
)


# --------------------------------------------------------------- small helpers
def cell(text: str) -> str:
    """A table cell. A stray pipe would silently split a column in two."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def band_rows() -> list[tuple[str, str, str]]:
    """The band table, derived by running band() rather than transcribed.

    Transcribing it is how a guide ends up describing thresholds the code
    stopped using. The range 0..20 covers every aggregate four parameters can
    produce and then some.
    """
    rows: list[tuple[str, str, str]] = []
    start = 0
    for total in range(21):
        here = band(total, False)
        nxt = band(total + 1, False) if total < 20 else None
        if nxt is not here:
            span = f"{start}" if start == total else f"{start}\u2013{total}"
            if total == 20:
                span = f"{start} or more"
            rows.append((span, here.value, here.response))
            start = total + 1
    return rows


def single_param_escalates_to() -> Urgency:
    """What one parameter scoring 3 does on its own, asked of the code."""
    return band(0, True)


def scenarios() -> list[tuple[str, str, str]]:
    """(endpoint name, title, description) for every scenario file.

    Parsed with regexes rather than PyYAML on purpose: this module is
    stdlib-only. It reads two fields out of files this repository owns, not
    arbitrary YAML, and if a file ever stops matching it falls back to the
    filename instead of failing the build of a document.
    """
    found = []
    for path in sorted(SCENARIO_DIR.glob("*.yaml")):
        text = path.read_text(encoding="utf-8")
        title = ""
        match = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
        if match:
            title = match.group(1).strip().strip("\"'")
        description = ""
        block = re.search(r"^description:\s*(>[-+]?|\|[-+]?)?\s*\n((?:[ \t]+.*\n?)+)",
                          text, re.MULTILINE)
        if block:
            description = " ".join(line.strip() for line in block.group(2).splitlines())
        else:
            inline = re.search(r"^description:\s*(.+)$", text, re.MULTILINE)
            if inline:
                description = inline.group(1).strip().strip("\"'")
        found.append((path.stem, title or path.stem, description.strip()))
    return found


# ------------------------------------------------------------------- the guide
def build() -> str:
    ship, ai, server = CONFIG.ship, CONFIG.ai, CONFIG.server
    url = f"http://{server.host}:{server.port}"
    zones = ", ".join(ship.quarantine_zones)
    beds = len(ship.quarantine_zones) * ship.zone_capacity
    works, needs = (
        [c for c in CAPABILITIES if not c["needs_ai"]],
        [c for c in CAPABILITIES if c["needs_ai"]],
    )

    p: list[str] = []
    w = p.append

    w(BANNER)
    w("")
    w("# MedBox \u2014 operator's guide")
    w("")
    w(f"**{ship.name} \u00b7 {ship.crew_size} crew \u00b7 no doctor aboard, "
      "no contact with Earth.**")
    w("")
    w("> **This is a research and education instrument. It is not a medical "
      "device and it does not diagnose.** It gives you an urgency ordering "
      "computed from a published clinical score, and an assistant that offers "
      "hypotheses with the reading behind each one. Every number on the screen "
      "can be traced back to the instrument that produced it.")
    w("")

    # -- 1 ---------------------------------------------------------------
    w("## 1. The one thing to understand first")
    w("")
    w("The box runs on two tracks, and they are not equally important.")
    w("")
    w("The **fast track** reads the sensors, scores each crew member with "
      "NEWS2 and redraws the board. It has no AI in it anywhere. It cannot be "
      "slowed down, confused or talked out of a reading.")
    w("")
    w("The **slow track** is the assistant. It suggests, it narrates, it "
      "listens. It is allowed to be slow and it is allowed to die.")
    w("")
    w("You do not need to remember which of your tools belong to which track, "
      "because the guide on the screen marks them and so does this one. But "
      "when somebody asks you on Friday what happens if the AI fails, the "
      "answer is: the vitals keep updating, the ordering holds, quarantine "
      "still assigns berths, the session still records, and the assistant "
      "stops narrating. The station's own spoken alerts carry on, starting "
      "with one that says the assistant has stopped. That is all.")
    w("")

    # -- 2 ---------------------------------------------------------------
    w("## 2. Starting the station")
    w("")
    w("One command, one process, one port. The interface is served by the same "
      "program that reads the sensors, so there is no second thing to start and "
      "nothing to configure.")
    w("")
    w("```")
    w("Linux / macOS    .venv/bin/python medbox.py")
    w("Windows          .\\.venv\\Scripts\\python medbox.py")
    w("```")
    w("")
    w(f"Then open <{url}>.")
    w("")
    w("If that is the first time on this machine, run the installer first "
      "(`./setup.sh`, or `powershell -ExecutionPolicy Bypass -File setup.ps1`). "
      "It is described in `README.md` and it is safe to run again at any time.")
    w("")
    w("You get two views of the same station, live at the same time:")
    w("")
    w("| Where | What it is | When to use it |")
    w("|---|---|---|")
    w(f"| `{url}/` | The ship. A 3D deck plan, crew at their stations, "
      "bulkheads that close. | The demo. |")
    w(f"| `{url}/board` | The flat board. Same data, no 3D. | A machine with "
      "no working WebGL, or a projector that hates you. |")
    w("")
    w("Both read the same feed and update together: the readings, the "
      "ordering, quarantine and the assistant are the same on both. The flat "
      "one has no Help panel, no command box and no spoken alerts, so on a "
      "machine that can run the ship, present from the ship.")
    w("")

    # -- 3 ---------------------------------------------------------------
    w("## 3. Reading the board")
    w("")
    w("The crew are ordered by NEWS2 aggregate, worst at the top. The ordering "
      "is the product: you should never have to hunt for the person who needs "
      "you.")
    w("")
    w("Each row carries the crew member, their four vitals, the aggregate, and "
      "the band that aggregate falls in.")
    w("")
    w("| NEWS2 aggregate | Band | What the score means you do |")
    w("|---|---|---|")
    for span, name, response in band_rows():
        w(f"| {cell(span)} | **{cell(name)}** | {cell(response)} |")
    w("")
    w(f"**The rule people forget:** any single parameter scoring 3 on its own "
      f"escalates to **{single_param_escalates_to().value}**, whatever the "
      "aggregate says. One catastrophic reading in an otherwise calm set is "
      "exactly the patient a total would hide, so the box applies the rule and "
      "tells you it did.")
    w("")
    w("Along the top of the window are the indicators. The ship labels them "
      "short and the flat board labels them long; they are the same three "
      "lights.")
    w("")
    w("| On the ship | On the board | Means |")
    w("|---|---|---|")
    w("| **link** | **Screen link** | This screen is receiving the live feed. "
      "If it goes dark, this browser lost the connection \u2014 the station is "
      "probably fine, reload the page. |")
    w("| **assistant** | **AI narration** | Whether the assistant is "
      "answering. Dark is a supported state, not an error. If it reads "
      "**stand-in, not a model**, something that is not a language model is "
      "answering, and the station says so before it shows you a word of it. |")
    w("| **no scenario** | **No scenario running** | Which rehearsed timeline "
      "is running, if any. |")
    w("")
    w("A fourth marker appears only during an outbreak, in red, when a crew "
      "member needs isolation and the ship has no berth left. See section 8.")
    w("")

    # -- 4 ---------------------------------------------------------------
    w("## 4. Looking at one crew member")
    w("")
    w("Click a row, on either view. You get their four vitals, and next to "
      "each one the reason it earned the points it earned.")
    w("")
    w("You also get the list of parameters that were actually **measured**. "
      "NEWS2 has seven; this box has instruments for four. A parameter nobody "
      "measured scores zero, and a zero that means \u201cnormal\u201d and a zero that "
      "means \u201cnobody looked\u201d are not the same thing. The panel says which, "
      "every time, so the screen never implies more confidence than the "
      "hardware earned.")
    w("")

    # -- 5 ---------------------------------------------------------------
    w("## 5. Recording what someone tells you")
    w("")
    w("Under **in their own words**, type what the crew member said and press "
      "Add. If a speech model is installed you also get a **Hold to speak** "
      "button: hold it, talk, release. What you said is transcribed on this "
      "machine and stored as their words.")
    w("")
    w("A reported symptom is never a measurement, so it **never changes the "
      "NEWS2 score.** It is stored as a claim, shown as a claim, and handed to "
      "the assistant marked as a claim. Somebody saying they feel terrible does "
      "not move them up the board, and somebody saying they feel fine does not "
      "move them down.")
    w("")
    w("The microphone button stays hidden until a complete speech model is on "
      "this machine, because a button that fails on the first press is worse "
      "than no button. Typing works throughout, model or no model. Fetching "
      "the model is one command and it is in `README.md`.")
    w("")

    # -- 6 ---------------------------------------------------------------
    w("## 6. Asking the assistant")
    w("")
    w("Select a crew member, press **Ask the assistant**. It reads that "
      "person's measurements and anything they reported, and comes back with:")
    w("")
    w("- **One sentence** on what the instruments recorded.")
    w("- **Up to three patterns**, most supported first. Each is a pattern, "
      "not a diagnosis, and each carries the signs behind it.")
    w("- **Where each sign came from.** Every sign names its instrument "
      f"(*{', '.join(SIGN_SOURCES[:-1])}*) or is marked as something the crew "
      "member said and no instrument recorded.")
    w("- **How much of the data the pattern accounts for** \u2014 "
      f"{', '.join(chr(8220) + f + chr(8221) for f in FIT_LEVELS)}. That is "
      "not a confidence "
      "score. A small model has no way to know how sure it is; it can tell you "
      "how much of the data a pattern covers.")
    w("- **What to ask them next.** The box measures four things and a person "
      "can tell you a hundred, so this is often the most useful part.")
    w("- **What to find out next.** Observations and measurements, never "
      "treatments.")
    w("")
    w("When the four measured parameters support nothing, it is allowed to say "
      "so and return no patterns at all. A crew member whose every reading is "
      "normal is allowed to have nothing wrong with them.")
    w("")
    w("An assessment is stamped with the score it was written against. If the "
      "person's vitals move after you asked, the panel tells you the answer is "
      "stale rather than quietly leaving it on screen.")
    w("")
    w(f"The model is `{ai.model}`, running on this machine through Ollama. It "
      "has a hard "
      f"{ai.timeout_seconds:g}-second ceiling. Past that the request is "
      "abandoned and you are told so \u2014 the box never waits on it.")
    w("")

    # -- 7 ---------------------------------------------------------------
    w("## 7. When the assistant is dead")
    w("")
    w("Kill Ollama mid-consultation. Nothing on the fast track notices.")
    w("")
    w("What changes: the **AI narration** indicator goes dark, **Ask the "
      "assistant** reports that it is unavailable, and the station says out "
      "loud that the assistant has stopped. Every other feature in this guide "
      "keeps working, including "
      "the guide on the screen \u2014 it is rendered from data the station owns, "
      "not from the model, so the thing explaining the system does not vanish "
      "at the moment the system is proving it does not need it.")
    w("")
    w("This is why the two lists in section 9 are split the way they are.")
    w("")

    # -- 8 ---------------------------------------------------------------
    w("## 8. Quarantine")
    w("")
    w("A crew member is isolated when they show a respiratory-transmissible "
      "pattern: a fever together with either falling oxygen or raised "
      "respiration. The rule is deliberately simple, because when somebody "
      "asks why a specific person was sealed into a specific zone, the answer "
      "has to be one sentence.")
    w("")
    w(f"There are {len(ship.quarantine_zones)} zones ({zones}), "
      f"{ship.zone_capacity} berths each, {beds} in total. A zone counts as "
      "**sealed** from the moment one person is inside it \u2014 you do not wait "
      "for a quarantine bay to fill before closing the door. Capacity governs "
      "something else: a zone at capacity stops taking new arrivals, and the "
      "next patient is placed in the next zone with room.")
    w("")
    w(f"When all {beds} berths are taken, anyone else is listed as **awaiting "
      "a bed**. They stay on the register with no zone, and they are drawn in "
      "red on both views — under the quarantine panel on the flat board, and "
      "as a marker along the top of the ship. A vessel that has run out of "
      "isolation space is the single most important fact on the screen, so it "
      "is never left to be inferred from a roster that is shorter than it "
      "should be.")
    w("")
    w("Isolation is released automatically when the pattern clears.")
    w("")

    # -- 9 ---------------------------------------------------------------
    w("## 9. Everything it does")
    w("")
    w("This is the same list the Help button shows, from the same source.")
    w("")
    w("### Works with the assistant dead")
    w("")
    for c in works:
        w(f"**{c['title']}**  ")
        w(f"{c['does']}  ")
        w(f"*{c['how']}*")
        w("")
    w("### Needs the assistant")
    w("")
    for c in needs:
        w(f"**{c['title']}**  ")
        w(f"{c['does']}  ")
        w(f"*{c['how']}*")
        w("")
    w(f"{len(works)} of the {len(CAPABILITIES)} things this box does need no "
      "model at all. That ratio is the honest shape of the product: the AI is "
      "a narrator over a system that works without it.")
    w("")

    # -- 10 --------------------------------------------------------------
    w("## 10. Everything it will never do")
    w("")
    w("Not policy, not a prompt asking it nicely. Each of these is enforced "
      "somewhere it cannot be talked out of.")
    w("")
    for r in REFUSALS:
        w(f"**{r['never']}.** {r['why']}")
        w("")

    # -- 11 --------------------------------------------------------------
    w("## 11. What you can type")
    w("")
    w("The ship view has a command box: press `/` and type. The microphone is "
      "for what a crew member tells you, and files it as their own words, so a "
      "phrase spoken into it is recorded, not run.")
    w("")
    w("| Phrase | Does | Needs the assistant |")
    w("|---|---|---|")
    for s in SHORTCUTS:
        mark = "yes" if s["needs_ai"] else "\u2014"
        w(f"| `{cell(s['phrase'])}` | {cell(s['does'])} | {mark} |")
    w("")
    w("`said` takes the rest of the line: `said I have had a headache since "
      "this morning`.")
    w("")

    # -- 12 --------------------------------------------------------------
    w("## 12. Running a scenario")
    w("")
    w("A scenario is a rehearsed timeline applied to the synthetic crew. "
      "Pick one at the top of the window and press **Run**; **Reset** returns "
      "the crew to nominal.")
    w("")
    for stem, title, description in scenarios():
        w(f"**{title}** (`{stem}`)  ")
        w(description or "\u2014")
        w("")
    w("**Demo from a scenario, never from live sensors.** A rehearsed replay "
      "cannot embarrass you in front of a jury. Live hardware can.")
    w("")

    # -- 13 --------------------------------------------------------------
    w("## 13. When something is wrong")
    w("")
    w("| What you see | What it is | What to do |")
    w("|---|---|---|")
    w("| The board is empty and says *waiting for the station* | The page "
      "loaded but the live feed has not connected | Reload. If it persists, "
      "the station is not running \u2014 start `medbox.py` again. |")
    w("| **Screen link** dark, numbers frozen | This browser lost the feed | "
      "Reload the page. The station kept running and kept recording. |")
    w("| **AI narration** dark | Ollama is not running, or not installed | "
      "Nothing breaks. If you want it back, start Ollama and the indicator "
      "comes back on its own. |")
    w("| *The assistant cannot answer* | It was asked and it failed or timed "
      "out | The reason is printed under the message. Vitals and triage are "
      "unaffected. |")
    w("| No **Hold to speak** button | No speech model on this machine | "
      "Typing works. To add it, see *Hold-to-speak* in `README.md`. |")
    w("| The 3D view is black or will not load | No working WebGL on this "
      "machine | Use the flat board at `/board`. It has the same data. |")
    w("| Nobody is being isolated during the outbreak | Isolation needs a "
      "fever **and** either falling oxygen or raised respiration | Check the "
      "individual vitals; fever alone is monitored, not isolated. |")
    w("")

    # -- 14 --------------------------------------------------------------
    w("## 14. What is on this machine, and what is not")
    w("")
    w("| | |")
    w("|---|---|")
    w(f"| Model | `{ai.model}`, running locally through Ollama |")
    if ai.fallback_models:
        w(f"| If that model is missing | `{'`, `'.join(ai.fallback_models)}` |")
    w(f"| Ollama version this is built against | {ai.required_ollama} |")
    w("| Speech out | Pre-rendered clips in the repository. Nothing to "
      "install. |")
    w("| Speech in | Transcribed on this machine. Audio never leaves it. |")
    w(f"| Data | A local SQLite file (`{CONFIG.database.path}`). |")
    w("| Network | None is used, at any point, by any part of this. |")
    w("")
    w("The browser's own speech API was deliberately not used: it ships the "
      "microphone audio to a Google endpoint, which is not something a product "
      "whose claim is *offline* can quietly do.")
    w("")
    w("---")
    w("")
    w("*Rebuild this document with `python tools/guide.py`. It is generated "
      "from the product, so it cannot describe a version of MedBox that does "
      "not exist.*")

    return "\n".join(p).rstrip() + "\n"


# --------------------------------------------------------------------- the cli
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build docs/USER_GUIDE.md.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the committed guide is out of date",
    )
    args = parser.parse_args(argv)

    fresh = build()

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} does not exist. Run: python tools/guide.py")
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current == fresh:
            print(f"{OUT.relative_to(ROOT)} is up to date.")
            return 0
        print(f"{OUT.relative_to(ROOT)} is out of date. Run: python tools/guide.py\n")
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                fresh.splitlines(keepends=True),
                fromfile="committed",
                tofile="generated",
            )
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    changed = not OUT.exists() or OUT.read_text(encoding="utf-8") != fresh
    OUT.write_text(fresh, encoding="utf-8")
    print(
        f"{'Wrote' if changed else 'Unchanged'} {OUT.relative_to(ROOT)} "
        f"({len(fresh.splitlines())} lines)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
