/* The one place an assistant's answer is turned into pixels.
 *
 * Both views used to render this separately, and a safety audit found the two
 * copies had already drifted: a rule enforced in one was absent from the
 * other. So there is now one renderer, loaded by index.html and ship.html
 * alike, and MedBox.assessment is the only function allowed to draw AI output.
 *
 * It holds three lines that the server cannot hold on its own, because they
 * are properties of the layout rather than of the data:
 *
 * 1. Every assessment carries a provenance banner, unconditionally. The old
 *    interface labelled its output only when a stand-in produced it, which
 *    meant that in the configuration a jury actually sees — a real model
 *    running — the AI region was the one place on screen with nothing saying
 *    where it came from. It sat directly beneath "7 / HIGH / Emergency
 *    response" in the same panel and the same typeface, and a reader fuses
 *    those into a single clinical statement.
 *
 * 2. A sign nobody measured is marked, in the sign, in a different colour.
 *    "Crushing chest pain radiating to the left arm" and "SpO2 89%" are not
 *    the same kind of fact and must not look like it.
 *
 * 3. An assessment goes stale. Vitals stream ten times a second and the band
 *    above redraws on every frame, while the text below is however old it is.
 *    Run a contamination scenario, assess somebody at ROUTINE, and forty
 *    seconds later "no pattern in the measured parameters" is still sitting
 *    under a band that now says HIGH. The assistant is asserting something the
 *    instruments no longer record, with no bad model output involved at all.
 */
(function (root) {
  "use strict";

  var MAX_AGE_MS = 60000;

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  // What the crew member said is not what the box measured, and the interface
  // says so in the sign itself rather than trusting the reader to remember.
  var SOURCE_LABEL = {
    temperature: "temperature",
    spo2: "SpO2",
    pulse: "pulse",
    respiration: "respiration",
    reported_by_crew_member: "SAID, NOT MEASURED",
    unattributed: "NO SOURCE GIVEN"
  };

  function sign(s) {
    var src = s && s.source ? s.source : "unattributed";
    var measured = src !== "reported_by_crew_member" && src !== "unattributed";
    return '<li class="sign ' + (measured ? "measured" : "unmeasured") + '">' +
      '<span class="src">' + esc(SOURCE_LABEL[src] || src) + "</span>" +
      esc(s && s.text ? s.text : "") + "</li>";
  }

  /* Render one assessment. `body` is the server's response.
   *
   * `opts.flyable` is whether this view can actually fly the camera to the
   * crew member a claim came from. The 3D console can; the flat board has no
   * camera, and an affordance that does nothing when you press it is worse
   * than no affordance at all.
   *
   * Returns HTML; the caller decides where it goes. */
  function render(body, opts) {
    var b = body || {}, o = opts || {}, html = "";

    // Unconditional, and first. Not a footnote, not conditional on the
    // stand-in, not something the reader has to go looking for.
    if (b.stand_in) {
      html += '<div class="ai-provenance standin"><b>Stand-in, not a language model.</b> ' +
        "This came from tools/fake_ollama.py, which reads the vitals back and applies " +
        "fixed rules. It proves the path works. It is not the assistant thinking, and " +
        "it must never be presented as such.</div>";
    } else {
      html += '<div class="ai-provenance"><b>Generated by ' + esc(b.model || "the assistant") +
        ".</b> Not measured, not computed, not a diagnosis. The urgency above is NEWS2 " +
        "and nothing here can change it.</div>";
    }

    // What the guard took out. An operator who never sees the assistant
    // misbehave has no way to calibrate how far to trust it, so suppression is
    // reported rather than silent.
    if (b.blocked && b.blocked.length) {
      html += '<div class="ai-blocked"><b>Suppressed by the station</b><ul>' +
        b.blocked.map(function (x) { return "<li>" + esc(x) + "</li>"; }).join("") +
        "</ul></div>";
    }

    if (b.summary) html += '<p class="sum">' + esc(b.summary) + "</p>";

    if (b.insufficient_data && !(b.hypotheses || []).length) {
      // "All in range" is the station talking, so it is said only when NEWS2
      // agrees. The server now refuses the flag under any other band; this is
      // the second lock, for a response from before that rule existed.
      html += '<div class="nothing">' +
        (b.urgency_at_assessment === "routine" ? "The four measured parameters are all in range. " : "") +
        "The assistant has no hypothesis to offer, and says so rather than inventing " +
        "one. What they reported is not something this box can measure.</div>";
    }

    if (b.hypotheses && b.hypotheses.length) {
      html += "<h3>Hypotheses</h3>";
      html += b.hypotheses.map(function (h) {
        // A bolded condition name over signs that are all things somebody said
        // reads as a diagnosis however the fields are named. The station says
        // so on the hypothesis itself rather than hoping the reader notices
        // that every bullet under it is amber.
        var bare = h.no_measured_support
          ? '<span class="unbacked">Nothing this box measured supports this. ' +
            'It rests entirely on what was reported.</span>'
          : "";
        return '<div class="hyp' + (h.no_measured_support ? " unbacked-hyp" : "") +
          '"' + (o.flyable ? ' data-fly="1"' : "") + "><b>" + esc(h.name) + "</b>" +
          '<span class="conf">' + esc(h.fit || "") + "</span>" + bare + "<ul>" +
          (h.supporting_signs || []).map(sign).join("") + "</ul>" +
          (o.flyable ? '<span class="fly">click to fly to the source →</span>' : "") +
          "</div>";
      }).join("");
    }

    if (b.questions_for_patient && b.questions_for_patient.length) {
      html += "<h3>Ask the patient</h3><ul>" +
        b.questions_for_patient.map(function (q) { return "<li>" + esc(q) + "</li>"; }).join("") +
        "</ul>";
    }

    if (b.information_to_gather && b.information_to_gather.length) {
      // Deliberately NOT "Suggested protocol". That heading read as an order
      // set, over an unbounded list the model filled however it liked.
      html += "<h3>Find out next</h3><ul>" +
        b.information_to_gather.map(function (s) { return "<li>" + esc(s) + "</li>"; }).join("") +
        "</ul>";
    }

    return html;
  }

  /* Is what is on screen still true?
   *
   * `held` is the assessment as returned; `liveTotal` is the NEWS2 aggregate
   * showing right now. Returns null while it still holds, or the sentence to
   * put over it when it does not. */
  function staleness(held, liveTotal, nowMs) {
    if (!held) return null;
    var age = nowMs - (held.at || 0) * 1000;
    if (liveTotal != null && held.news2_at_assessment != null &&
        liveTotal !== held.news2_at_assessment) {
      return "These readings have changed since this was written. NEWS2 was " +
        held.news2_at_assessment + ", it is now " + liveTotal + ". Ask again.";
    }
    if (age > MAX_AGE_MS) {
      return "This was written " + Math.round(age / 1000) +
        " seconds ago. Ask again for the current readings.";
    }
    return null;
  }

  function failure(note) {
    return '<div class="fail"><b>Assistant unavailable</b>' +
      esc(note || "Vitals and triage are unaffected.") + "</div>";
  }

  root.MedBox = root.MedBox || {};
  root.MedBox.assessment = {
    render: render,
    staleness: staleness,
    failure: failure,
    MAX_AGE_MS: MAX_AGE_MS
  };
})(window);
